version: 2
updates:
- package-ecosystem: gomod
  directory: "/acceptance-tests"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/postgresqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/s3app"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/mysqlapp"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: gomod
  directory: "/acceptance-tests/apps/redisapp"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/s3/provision"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/s3/bind"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/redis/cluster/provision"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/dynamodb/provision"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/dynamodb/bind"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/rds/provision"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/rds/bind/postgresql"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: terraform
  directory: "/terraform/rds/bind/mysql"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
