name: Automerge Dependabot

on:
  pull_request:
    branches: [ main ]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
  automerge:
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: github.repository_owner,
              repo: github.repository,
              pull_number: context.payload.pull_request.number
            })
