name: Automerge Dependabot

on:
  pull_request:
    branches: [ main ]

jobs:
  automerge:
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Merge
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              name: context.repo,
              pull_number: context.issue.number
            })
